# Model structure
model:
  components: ['velocity', 'growth']
  velocity_net:
    hidden_dim: 400
    n_layers: 2
    residual: false
  growth_net:
    hidden_dim: 400
    n_layers: 2
    residual: false

# Training plan
training:
  # Default parameters
  defaults:
    lr: 0.0001
    lambda_ot: 1.0
    lambda_mass: 0.01
    lambda_energy: 0.01

  # Unbalanced OT uses a two-stage training plan
  plan:
    - name: "Pretrain"
      mode: "neural_ode"
      method: "ODEFunc"
      epochs: 500
      global_mass: False
      OT_loss: 'sinkhorn_detach'
      lambda_energy: 0.0
      scheduler_step_size: 500

    - name: "Train"
      mode: "neural_ode"
      method: "ODEFunc"
      epochs: 500
      global_mass: True
      OT_loss: 'sinkhorn'
      lambda_ot: 10
      lambda_mass: 10
      lambda_energy: 0.01